server:
  port: 8080
  http2:
    enabled: true
#  servlet:
#    context-path: /grpc
spring:
  datasource:
    url: jdbc:mysql://127.0.1:3306/test?characterEncoding=utf8&useSSL=true
    data-username: root
    data-password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  #  覆盖功能
  main:
    allow-bean-definition-overriding: true


#dubbo配置
dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
    id: spring-dubbo-demo
    check: false
    username: name
    password: super:password
  protocol:
    port: 20880
    name: dubbo
    status: server
    id: spring-dubbo-demo
    serialization: protobuf
    optimizer: com.sky.grpc.dubbo.serialize.SerializationOptimizerImpl
  application:
    name: spring-dubbo-demo
    id: spring-dubbo-demo
    qos-enable: true
    qosPort: 22223
  scan:
    basePackages: com.sky.grpc.dubbo
  provider:
    timeout: 300000
    serialization: protobuf
  consumer:
    timeout: 300000



#配置其他注册中心
registry:
  other:
    protocol: zookeeper
    address: 127.0.0.1:2181
    id: other